version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: redis
    container_name: redis
    restart: always
    networks:
      - app-network
    depends_on:
      - nodejs
    volumes:
      - redis-storage:/data

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/letsencrypt
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network

volumes:
  redis-storage:
    driver: local
    driver_opts:
      type: none
      device: /home/docker_nginx_snode_ssl/redis_storage/
      o: bind
  certs:
    driver: local
    driver_opts:
      type: none
      device: /home/docker_nginx_snode_ssl/ssl_storage/
      o: bind
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/docker_nginx_snode_ssl/views/
      o: bind
networks:
  app-network:
    driver: bridge