version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - nodejs

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - nodejs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    #command: certonly --webroot --webroot-path=/var/www/html --email biryukwolf1@gmail.com --agree-tos --no-eff-email --staging -d lookbest.tk  -d www.lookbest.tk
    command: certonly --webroot --webroot-path=/var/www/html --email biryukwolf1@gmail.com --agree-tos --no-eff-email --force-renewal -d lookbest.tk -d www.lookbest.tk


volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/node_project/views/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/node_project/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge